### ISSUE TITLE
"graphqlservice/IntrospectionSchema.h" file is not found

### ISSUE THREAD

**Issue by stijnfrishert** [microsoft/cppgraphqlgen#105] opened 2020-05-23 19:36 UTC
First of all: really excited to be using this library. Seems like a good modern solution for GraphQL in cpp. :)

I'm running schemagen and a .cpp and .h come rolling out, but get a compilation error when I try to compile the source file. The generated.cpp contains the following line:

```
#include "graphqlservice/Introspection.h"
```

which, in turn, contains this line:

```
#include "graphqlservice/IntrospectionSchema.h"
```

But `IntrospectionSchema.h` is nowhere to be found? Should that also be generated? If so, that doesn't seem to be happening, and if not, I can't find it in the repository anywhere.

Using the master branch, compiling with Xcode on macOS.

**Comment by wravery** [comment] 2020-05-23 21:25
Normally that's generated and installed in the public include directory with `cppgraphqlgen` itself. If you are building from source rather than using something like `vcpkg`, you will probably need to run `cmake --install` with parameters telling it where to put the headers and libraries, and then you'll need to add the installed include directory to your include search path.

**Comment by stijnfrishert** [comment] 2020-05-24 06:44
Right, so I can't really use cppgraphqlgen in CMake as is, by just `target_link_libraries`-ing the exposed targets? That's a bit contrary to how I'm used to work with CMake, but I'll give it a try.

**Comment by stijnfrishert** [comment] 2020-05-24 09:50
Hmmm, when running `cmake --install . --prefix <my-folder>` I do get a an install, but still no `IntrospectionSchema.h`

![image](https://user-images.githubusercontent.com/7056711/82751033-bd127900-9db4-11ea-9318-4d4567935ce9.png)

**Comment by wravery** [comment] 2020-05-24 18:35
Interesting, maybe this is something specific to using Xcode as the generator. I've just been using makefiles/Ninja on the Mac and haven't run into this. I'll give Xcode a try.

**Comment by wravery** [comment] 2020-05-25 20:39
I haven't been able to reproduce this yet with Xcode, it seems to work OK on my Mac.

@stijnfrishert are you specifying `-DCMAKE_BUILD_TYPE=Release` when configuring the build? There's some installation logic which I suppressed in debug builds, largely because `vcpkg` has errors if you try to install headers and docs/config for both debug and release flavors.

If that's what's causing this, I can switch the conditional install logic to check an `option()` variable instead of just looking at the `CMAKE_BUILD_TYPE`, and then make the `vcpkg` port set the option on debug rather than suppressing it for all debug installs. But I want to confirm whether setting the variable at config time works first or if there's something more to your setup that I'm not getting.

**Comment by stijnfrishert** [comment] 2020-06-14 09:28
@wravery, would it be too much to ask if you could set out the exact build/install steps when building from source?

I've `git submodule add`-ed the repo with your latest pull request, but find it confusing how to use the library in an existing CMake project. 😕

**Comment by stijnfrishert** [comment] 2020-06-16 16:05
I've given this another try, but to no avail. Here are my steps when inside the cppgraphqlgen folder:

```
mkdir build
cd build
cmake -DGRAPHQL_BUILD_TESTS=OFF -DGRAPHQL_UPDATE_SAMPLES=OFF -DGRAPHQL_USE_RAPIDJSON=OFF -
DGRAPHQL_INSTALL_CMAKE_DIR=../output -DGRAPHQL_INSTALL_TOOLS_DIR=../output ..
cmake --build . --target install
```

This builds `graphqlpeg`, `graphqlresponse` and `schemagen` successfully, but I still get the same error when it's building `graphqlservice`.

Also, this ^ is using Makefiles, so Xcode can't be the problem.

**Comment by wravery** [comment] 2020-06-17 20:08
OK, I'll take another look.

**Comment by wravery** [comment] 2020-06-27 18:49
Ah, I think I found the problem, thank you for the detailed repro steps. In the case where `GRAPHQL_UPDATE_SAMPLES=OFF`, it doesn't make the directory before copying `IntrospectionSchema.h` to `include/graphqlservice`, so there's a file called `graphqlservice` in the build/include directory which is a copy of `IntrospectionSchema.h`:

```cmake
else()
  add_custom_command(
    OUTPUT
      ${CMAKE_CURRENT_BINARY_DIR}/../IntrospectionSchema.cpp
      ${CMAKE_CURRENT_BINARY_DIR}/../include/graphqlservice/IntrospectionSchema.h
    COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/../samples/introspection/IntrospectionSchema.cpp .
    COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/../samples/introspection/IntrospectionSchema.h include/graphqlservice
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/..
    COMMENT "Copying IntrospectionSchema files")
endif()
```

**Comment by wravery** [comment] 2020-06-27 18:57
BTW, a simpler way to handle the install step would be to specify `-DCMAKE_INSTALL_PREFIX=../output` instead of overriding each of those `GRAPHQL_INSTALL_...` defaults. Those won't override the library install path, so by default it'll still try to install to a system directory and require a password.

I'm not sure if the install step will still be necessary or if needing that was a combination of the bugs you found. Once I get a fix for the `GRAPHQL_UPDATE_SAMPLES=OFF` merged I'll experiment with adding `cppgraphqlgen` as a sub-directory rather than as a separately installed lib.

**Closed** 2020-06-27 19:56 UTC

**Comment by wravery** [comment] 2020-06-27 19:58
I got the sub-directory/sub-module build working, but note that you'll either need to recursively clone the `cppgraphqlgen` repo/sub-module to its `PEGTL` sub-module, or you'll still need to install `PEGTL` separately to do this.

**Comment by stijnfrishert** [comment] 2020-07-03 09:21
Cool, thanks! I'll give it another try :)
